In [1]:
import numpy as np

In [3]:
my_list=[1,2,3,4]
arr=np.array(my_list)

In [4]:
type(arr)

numpy.ndarray

In [5]:
print(arr)

[1 2 3 4]


In [10]:
#mulitdimensional array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [11]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [12]:
arr.shape

(3, 5)

In [13]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [14]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [16]:
#indexing of multidimensional array
arr.shape

(3, 5)

In [17]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [22]:
#arr(start_row:range_row:start_column:range_column)
arr[0:2,0:5]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [25]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [31]:
arr=[1,7,9,4,5,6]

In [35]:
arr=np.arange(0,10)

In [36]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
#arange with certain gap np.arange(start,end,step)
arr=np.arange(0,10,2)

In [38]:
arr

array([0, 2, 4, 6, 8])

In [39]:
arr[3:]=100

In [40]:
arr

array([  0,   2,   4, 100, 100])

In [41]:
arr=np.array([1,2,3,4,5,6])

In [42]:
arr[2:]=20

In [43]:
arr

array([ 1,  2, 20, 20, 20, 20])

In [44]:
arr[2:]=100

In [45]:
arr

array([  1,   2, 100, 100, 100, 100])

In [47]:
#this causes to refer same memory location by both array name
arr1=arr

In [55]:
#if arr1 is changed then values of arr also changes
arr1[2:]=500

In [56]:
arr

array([  1,   2, 500, 500, 500, 500])

In [57]:
#use arr.copy() to preserve both array
arr1=arr.copy()

In [58]:
arr1

array([  1,   2, 500, 500, 500, 500])

In [59]:
arr1[0:]=10

In [60]:
arr1

array([10, 10, 10, 10, 10, 10])

In [61]:
arr

array([  1,   2, 500, 500, 500, 500])

In [62]:
#gives which values are less than 2
arr<2

array([ True, False, False, False, False, False])

In [64]:
arr[arr<=2]

array([1, 2])

In [65]:
#multiplies every item with 2
arr*2

array([   2,    4, 1000, 1000, 1000, 1000])